export const CONTACT_ACTION_TYPES = {
    GET: {
        ACTION: 'GET_CONTACTS_ACTION',
        REQUEST: 'GET_CONTACTS_REQUEST',
        SUCCESS: 'GET_CONTACTS_SUCCESS',
        ERROR: 'GET_CONTACTS_ERROR'
    },
    ADD: {
        ACTION: 'ADD_CONTACT_ACTION',
        REQUEST: 'ADD_CONTACT_REQUEST',
        SUCCESS: 'ADD_CONTACT_SUCCESS',
        ERROR: 'ADD_CONTACT_ERROR'
    },
    UPDATE: {
        ACTION: 'UPDATE_CONTACT_ACTION',
        REQUEST: 'UPDATE_CONTACT_REQUEST',
        SUCCESS: 'UPDATE_CONTACT_SUCCESS',
        ERROR: 'UPDATE_CONTACT_ERROR'
    },
    DELETE: {
        ACTION: 'DELETE_CONTACT_ACTION',
        REQUEST: 'DELETE_CONTACT_REQUEST',
        SUCCESS: 'DELETE_CONTACT_SUCCESS',
        ERROR: 'DELETE_CONTACT_ERROR'
    }
};

export const EDITABLE_CONTACT_ACTION_TYPE = 'EDITABLE_CONTACT_ACTION_TYPE';
